repos:
  # Detect secrets and prevent committing sensitive data
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [
          "--in-place",
          # "--remove-all-unused-imports",
          # "--remove-unused-variables",
          "--expand-star-imports"
        ]
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
      args: [--line-length=120]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [
          "--extend-ignore=E203,E704",
          "--max-line-length=120"
        ]
  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.2
    hooks:
      - id: pylint
        exclude:
            (?x)(
                ^docs
                | ^tests/
                | ^cookbook/
                | ^cookbooks/
                | ^tutorials/
                | pb2\.py$
                | grpc\.py$
                | \.demo$
                | \.md$
                | \.html$
          )
        args: [
          --disable=W0511,
          --disable=W0718,
          --disable=W0122,
          --disable=C0103,
          --disable=R0913,
          --disable=R0917,
          --disable=E0401,
          --disable=E1101,
          --disable=E1111,
          --disable=C0415,
          --disable=W0603,
          --disable=R1705,
          --disable=R0914,
          --disable=E0601,
          --disable=W0602,
          --disable=W0604,
          --disable=R0801,
          --disable=R0902,
          --disable=R0903,
          --disable=R0904,
          --disable=C0123,
          --disable=W0231,
          --disable=W1113,
          --disable=W0221,
          --disable=R0401,
          --disable=W0632,
          --disable=W0123,
          --disable=C3001,
          --disable=R1702,
          --disable=R0912,
          --max-line-length=120,
        ]
  - repo: https://github.com/regebro/pyroma
    rev: "5.0"
    hooks:
      - id: pyroma
        args: [--min=10, .]
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
          "--ignore=tests/graders/multimodal",
          "--ignore=tests/generator",
          "--ignore=data",
          "--ignore=examples"
        ]